### ISSUE TITLE
The default-user field is incorrect

### ISSUE THREAD

**Issue by tomasbasham** [exoscale/packer-plugin-exoscale#10]
Recently I am receiving errors when trying to use this packer plugin whereas previously I had no problems. When I attempt to create a new instance template the following is returned causing the build to halt.

```
==> exoscale.my_template: Stopping Compute instance
==> exoscale.my_template: Creating Compute instance snapshot
==> exoscale.my_template: Exporting Compute instance snapshot
==> exoscale.my_template: Registering Compute instance template
==> exoscale.my_template: unable to register template: Post "https://api-ch-dk-2.exoscale.com/v2/template": invalid request: the default-user field is incorrect
==> exoscale.my_template: Cleanup: destroying Compute instance
==> exoscale.my_template: Cleanup: deleting SSH key
Build 'exoscale.my_template' errored after 4 minutes 43 seconds: build halted
```

The API documentation for this endpoint specifies that the `default-user` be a an optional string. Even the [documentation](https://github.com/exoscale/packer-plugin-exoscale/blob/main/docs/builders/exoscale.md) of the plugin specifies this field is optional.

This is the configuration I am using. I suspect if I add `template_username` to the configuration the build will continue to completion.

```hcl
source "exoscale" "my_template" {
  api_key    = "${var.exoscale_api_key}"
  api_secret = "${var.exoscale_api_secret}"

  instance_template  = "${var.exoscale_image}"
  instance_disk_size = var.exoscale_size
  ssh_username       = "${var.exoscale_ssh_username}"

  template_name        = "my-template-${local.build_time}"
  template_zone        = "${var.exoscale_region}"
  template_boot_mode   = "uefi"
}
```

**Comment by falzm** [comment]
Hello @tomasbasham, thank you for reporting this issue. This is a known bug in the Exoscale API that we are currently working on fixing, in the meantime as a workaround you must set a value for the `template_username` parameter (as well as for `template_description`).

We apologize for the inconvenience.

**Comment by tomasbasham** [comment]
@falzm Thanks for the speedy reply. I'm glad to hear it is being work on. I can confirm everything works when adding those fields.

**Comment by falzm** [comment]
Happy to hear 👍  I'll go ahead and close this issue now, as it doesn't pertain directly to a bug in the Exoscale Packer plugin.
